### ISSUE TITLE
Zeitungsartikel

### ISSUE THREAD

**Issue by ASG-Reitmaier** [stefhol/inn.kubator.dashboard#2]
Hallo Stefan,

ich würde gerne auf der ASG-Homepage einen Artikel über den Hackerthon und ebenso einen Zeitungsartikel in der PNP veröffentlichen. Wäre es ok, wenn ich das Foto verwende auf dem du und Tobias abgebildet sind?

Viele Grüße
Christian

**Comment by stefhol** [comment]
Hi Christian,

ich hoffe doch dir wurde die Email mit der Erlaubnis weitergeleitet

Gruss
Stefan

**Comment by ASG-Reitmaier** [comment]
Servus,

ich habe vom Mara noch nichts bekommen. Aber cool, dann packe ich das Bild, sobald Mara mir noch die weiteren Bilder schickt, in einem Artikel auf die Homepage.

Viele Grüße
Christian
